### ISSUE TITLE
Glass Panes

### ISSUE THREAD

**Issue by C1ffisme** [Sokomine/handle_schematics#3]
This is a simple problem, but glass panes do not get rotated during the process of copying a building.

If the building is small, then it is easy to manually change these panes, but if you have glass windows that are enormously large, then it could get quite tedious.

The simplest fix for this bug is to alias glass panes to their rotated copies and use them during a rotation, the hardest part being the aliasing.

By the way, remember to think about these nodes when you get to making a version of this mod for survival mode! :wink:

**Comment by Sokomine** [comment]
The current glass panes work fine, but there may always be changes to existing nodes that may require further adaptions in the future. Please try the latest version! Thanks.
